### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by flowersw** [borgnix/spacemacs-journal#1]
Thanks @borgnix  for creating this! I have had trouble installing it. 
1) Should it be installed as follows? ~/.emacs.d/private/spacemacs-journal ? 
2) When I added journal to my DOT file, spacemacs did not seem to recognize it.

Are there other caveats or layers that could affect the installation?

Thanks.

**Comment by ruibinx** [comment]
Sorry I made a mistake on installation guide.
Try `git clone https://github.com/borgnix/spacemacs-journal.git ~/.emacs.d/private/journal`.
This should work.

**Comment by ruibinx** [comment]
Or you could just change the folder name to `journal`.

**Comment by flowersw** [comment]
Thanks @borgnix , I think that solved it.

**Comment by x61** [comment]
this only works when you are on spacemacs `master` branch. It does not work when on `develop` branch. Is it possible to get it to work while on `develop` branch as well?
