### ISSUE TITLE
Can't access Major mode bindings? General questions

### ISSUE THREAD

**Issue by flowersw** [borgnix/spacemacs-journal#3]
Maybe this is just a lack of experience with the org-journal package, but I don't seem to be able to use major mode bindings when writing an entry. Also, are there settings/variables that are easily changeable,  such as the name of diaries that are created? Or is most of the configuration just found in the layer?

The diary entry appears to be created in org mode, but doesn't have a `.org` extension. 

Again these are more generic questions, that may be answered in the original org-journal package.

**Comment by ruibinx** [comment]
`journal-mode` is a derived mode of `org-mode`. All spacemacs keybindings for `org-mode` are defined in the `org` layer of spacemacs. They won't be evaluated when loading a `journal-mode` file. I am trying to find a solution to this. Before that, you could access `org-mode` by directly calling org mode functions.

About the configurations of `org-journal`, you could check them at https://github.com/bastibe/org-journal. Yes, the file format is changeable. You could set the variable `org-journal-file-format` directly. The doc of org-journal has a more specific description.

Anyway, feel free to ask :)

**Comment by ruibinx** [comment]
I have already pushed a few commits to copy all org-mode bindings for journal mode. 

I will close this issue for now. If there are still problems, reopen it please.

**Comment by flowersw** [comment]
Thanks @borgnix !
