### ISSUE TITLE
can't access global keybindings

### ISSUE THREAD

**Issue by skgbanga** [borgnix/spacemacs-journal#4]
Hey,

I did the installation steps:
1. git clone https://github.com/borgnix/spacemacs-journal.git ~/.emacs.d/private/journal
2. add it to your ~/.spacemacs. You will need to add journal to the existing dotspacemacs-configuration-layers list in this file.

However, I am not able able to get the global keybindings i.e. `SPC a j` is undefined. I have done `SPC f d R` as well as restarted the spacemacs, but to no avail.

**Comment by skgbanga** [comment]
Actually, ignore this. I am stupid. For some reason, I was under the impression that above would also install the org-journal for me. Once I put that in my dot file, I am able to see it now.

**Comment by rxing-ext-aa** [comment]
@skgbanga I think above steps would install the org-journal package for you. I wonder why it didn't work out for you. Maybe something wrong with your spacemacs configuration? You are welcome to reopen this issue if this problem still bothers you.

**Comment by ruibinx** [comment]
@skgbanga I think above steps would install the org-journal package for you. I wonder why it didn't work out for you. Maybe something wrong with your spacemacs configuration? You are welcome to reopen this issue if this problem still bothers you.

**Comment by skgbanga** [comment]
@borgnix I had to do this

     (org :variables
          org-enable-org-journal-support t)

Without it, I was not able to see the global key-bindings. (I am new to spacemacs (and emacs), so yes, there is a high likelihood, that I might be doing something wrong.)

**Comment by x61** [comment]
you don't get the same keybindings when you are on `develop` branch. How do I get the same keybindings defined here while on `develop` branch?
