### ISSUE TITLE
Major mode keybindings unbound

### ISSUE THREAD

**Issue by mdsib** [borgnix/spacemacs-journal#8]
It seems like org-mode's major map doesn't include the `j` prefix, which causes the major mode keybindings to not work. Adding the appropriate prefix fixes this for me. If it's as simple as that, and not some configuration bug / error on my end, I can make a PR with the change.

**Comment by ruibinx** [comment]
The official key bindings for journal mode in spacemacs have already been available on develop branch of spacemacs repository. So it's best for you to just change to develop branch or wait for 0.300 release. 

Please read https://github.com/syl20bnr/spacemacs/blob/develop/layers/%2Bemacs/org/README.org#org-journal for details.

**Comment by mdsib** [comment]
Cool, thanks for the info.
